language: node_js
node_js:
- '4.1'
scripts:
- npm test
deploy:
  provider: npm
  email: "sziklaszlo@gmail.com"
  api_key:
    secure: VP89F1U4cjb2xfBpvT1qoeiwxq42tAHUh5TV40zKv8FbTPEEDLbXmQwIYH2a8Ux83nWVPhO6LIqP1JP9Wrphf1uT86ck4RuP5xTqpo74mlC7HPWswqv8ggpCxYquuW8RpMXOPQGX6zOxA7tKHdoCusDf3LTS2qXeKdp0k76zgwCNiDZPz4GGwfjGIuKQcvxSztl6PHxHOgrdx7rEx2SNNiXUxe+rOTwA88fmAi3T92opZz6qZbU7litXoV8Ks0r38opsKPnja1cA/9DA/JlkJG4M/n7/Mvno3rQY3mgmaxCV/O++gyVRIbg35REVmbg5Xr8bjSFDWRO+k3WP1sIVytEV6oRbCv6mLMRZllfkIJ8YRMYLn7PhYFPYibo0qrZPruJa6/IVn00tA8Xu/ozPA2ZYShTZFsBYY4YO91DGfjXTSLKRRMebUtiutnPmvtWK4G5QfvqesdkzqL/VnhlbifZniwXClnsYrJ+oDMQp7Q5jo4c/5eXTxpA8eSfkcIJfeKp2ed2aFB0J1RC/ON0Ah9J5jBSC2svcEUKV12EEqLzQNIjN6PZJpUwRf8YPcFVVLoJuD3m5BVcTZQfC9AKGCCL+do68HMw+Bb1OuM2yPbxgOCyyioTPd+M+QjFDk7RCZw6uilHHLkmoHJ6YZo6UJ7W0S8f05SI4wn8I+b+25k8=
