name: Pull requests
on: [pull_request]
jobs:
  call_npm_package_build:
    uses: szikszail/workflows/.github/workflows/npm-package-build.yml@v1
    with:
      coverage_path: dist/reports/coverage/clover.xml